FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TrainingHelper.ApiGateway/TrainingHelper.ApiGateway.csproj", "TrainingHelper.ApiGateway/"]
RUN dotnet restore "./TrainingHelper.ApiGateway/TrainingHelper.ApiGateway.csproj"
COPY . .
WORKDIR "/src/TrainingHelper.ApiGateway"
RUN dotnet build "./TrainingHelper.ApiGateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TrainingHelper.ApiGateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TrainingHelper.ApiGateway.dll"]